### ISSUE TITLE
problemas con carga del proyecto

### ISSUE THREAD

**Issue by rurream** [mpachecoa/FundamentosAndroid#5]
Estimado Miguel Emerson Pacheco Alor, mi nombre es Rodrigo Urrea, somos compañeros de curso en Coursera. En el contexto de revisar tu trabajo te comento que tengo problemas al cargar tus archivos en Android Studio.
Con las dos versiones (master y branch), en Gradle Console tengo mensajes como el siguiente:

AGPBI: {"kind":"error","text":"No resource found that matches the given name (at \u0027drawable\u0027 with value \u0027@drawable/abc_textfield_search_activated_mtrl_alpha\u0027).", ...

No soy experto para nada en Android Studio, uso versión 2.3.1; tengo desabilitado el Instant Run.

Hasta donde veo, en el Build, se hace referencia a un recurso drawable que no se encuentra.

Espero tus comentarios, quizás un consejo para poder cargar tu proyecto, lo más pronto posible.

Saludos

**Comment by mpachecoa** [comment]
Estimado Rodrigo Urrea, por favor revisa lo siguiente:

1. La versión de compilación del SDK que indica el gradle es 25, por favor revisa en el SDK Manager si tienes instalada esa versión. 
2. La versión de Android Studio que utilizo es 2.3.0, al abrir el proyecto te aparece una ventana para actualizar la versión a 2.3.1 y Gradle 3.3, selecciona actualizar. Ya he actualizado la versión de Android Studio a 2.3.1 y he probado el proyecto bajandolo de GitHub y también funciona bien.

Espero que se solucione el problema, en todo caso me avisas que error te aparece. Gracias.

Saludos

**Comment by rurream** [comment]
Estimado, que bueno comunicarnos.
Mañana temprano reviso el tema y te comento.

Saludos

**Comment by rurream** [comment]
Estimado Miguel, ubicando el proyecto en la carpeta de Android Studio Proyects todo se ha resuelto. He podido cargar y visualizar tu aplicación y está correcta.

Saludos

**Comment by mpachecoa** [comment]
Que bueno!!!
Estamos en contacto.

Saludos
